#@ load("@ytt:data", "data")

#@yaml/text-templated-strings
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses: (@= str(data.values.metallb.addresses) @)
